name: VDF Patch Validator
description: Checks Daedalus script symbols and resource file names in a Gothic VDF patch for validity

branding:
  icon: check
  color: yellow

inputs:
  patchName:
    description: >
      Identifier of the patch, i.e. name of the VDF.
      Defaults to the repository name
    required: false
  rootPath:
    description: >
      Root path of the patch, i.e. the directory containing the Ninja directory and .validator.yml.
      Defaults to the repository root
    required: false
  token:
    description: >
      Github authentication token for authoring checks.
      Defaults to the github-actions bot
    default: ${{ github.token }}
  cleanup-token:
    description: >
      This input is for clean up actions and should always be left at its default.
    default: ${{ github.token }}

runs:
  using: node20
  main: dist/index.js
